version: '3.9'
services:
  sqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=2Secure*Password2
      - ACCEPT_EULA=Y
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-P2Secure*Password2", "-Q", "select 1"]
      interval: 20s
      retries: 20
    ports:
      - "1435:1433"
  volunteer-net-server:
    image: volunteer-net-server
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      sqldb:
        condition: service_healthy
    restart: on-failure
    ports:
      - "5000:80"